apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: "nginx"    
  name: grafana-ingress
spec:  
  rules:
  - host: grafana.kubeshore.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service: 
            name: grafana-np
            port: 
              number: 80
  tls:
  - hosts:
    - grafana.kubeshore.com
    secretName: grafana-tls              
